export const randomDate = (start: Date, end: Date) => {
  return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
};

export const GridRows = [
  { 
    id: 1, 
    receiptDate: 'Snow', 
    wagon: 'Jon', 
    type: 'Jon', 
    wheelPairNum: 'Jon', 
    manufacturerStamp: 'Jon', 
    created_at: randomDate(new Date(2012, 0, 1), new Date()).getFullYear(), 
    CKKLeft: 1, 
    CKKRight: 2, 
    rimThicknessLeft: 3, 
    rimThicknessRight: 4, 
    ridgeThicknessLeft: 6, 
    ridgeThicknessRight: 7, 
    wheelPairType: '1 вид', 
    note: 'Jon', 
  },
  { 
    id: 2, 
    receiptDate: 'Snow', 
    wagon: 'Jon', 
    type: 'Jon', 
    wheelPairNum: 'Jon', 
    manufacturerStamp: 'Jon', 
    created_at: randomDate(new Date(2012, 0, 1), new Date()).getFullYear(), 
    CKKLeft: 1, 
    CKKRight: 2, 
    rimThicknessLeft: 3, 
    rimThicknessRight: 4, 
    ridgeThicknessLeft: 6, 
    ridgeThicknessRight: 7, 
    wheelPairType: '1 вид', 
    note: 'Jon', 
  },
  { 
    id: 3, 
    receiptDate: 'Snow', 
    wagon: 'Jon', 
    type: 'Jon', 
    wheelPairNum: 'Jon', 
    manufacturerStamp: 'Jon', 
    created_at: randomDate(new Date(2012, 0, 1), new Date()).getFullYear(), 
    CKKLeft: 1, 
    CKKRight: 2, 
    rimThicknessLeft: 3, 
    rimThicknessRight: 4, 
    ridgeThicknessLeft: 6, 
    ridgeThicknessRight: 7, 
    wheelPairType: '1 вид', 
    note: 'Jon', 
  },
  { 
    id: 4, 
    receiptDate: 'Snow', 
    wagon: 'Jon', 
    type: 'Jon', 
    wheelPairNum: 'Jon', 
    manufacturerStamp: 'Jon', 
    created_at: randomDate(new Date(2012, 0, 1), new Date()).getFullYear(), 
    CKKLeft: 1, 
    CKKRight: 2, 
    rimThicknessLeft: 3, 
    rimThicknessRight: 4, 
    ridgeThicknessLeft: 6, 
    ridgeThicknessRight: 7, 
    wheelPairType: '1 вид', 
    note: 'Jon', 
  },
  { 
    id: 5, 
    receiptDate: 'Snow', 
    wagon: 'Jon', 
    type: 'Jon', 
    wheelPairNum: 'Jon', 
    manufacturerStamp: 'Jon', 
    created_at: randomDate(new Date(2012, 0, 1), new Date()).getFullYear(), 
    CKKLeft: 1, 
    CKKRight: 2, 
    rimThicknessLeft: 3, 
    rimThicknessRight: 4, 
    ridgeThicknessLeft: 6, 
    ridgeThicknessRight: 7, 
    wheelPairType: '1 вид', 
    note: 'Jon', 
  },
  { 
    id: 6, 
    receiptDate: 'Snow', 
    wagon: 'Jon', 
    type: 'Jon', 
    wheelPairNum: 'Jon', 
    manufacturerStamp: 'Jon', 
    created_at: randomDate(new Date(2012, 0, 1), new Date()).getFullYear(), 
    CKKLeft: 1, 
    CKKRight: 2, 
    rimThicknessLeft: 3, 
    rimThicknessRight: 4, 
    ridgeThicknessLeft: 6, 
    ridgeThicknessRight: 7, 
    wheelPairType: '1 вид', 
    note: 'Jon', 
  },
  { 
    id: 7, 
    receiptDate: 'Snow', 
    wagon: 'Jon', 
    type: 'Jon', 
    wheelPairNum: 'Jon', 
    manufacturerStamp: 'Jon', 
    created_at: randomDate(new Date(2012, 0, 1), new Date()).getFullYear(), 
    CKKLeft: 1, 
    CKKRight: 2, 
    rimThicknessLeft: 3, 
    rimThicknessRight: 4, 
    ridgeThicknessLeft: 6, 
    ridgeThicknessRight: 7, 
    wheelPairType: '1 вид', 
    note: 'Jon', 
  },
  { 
    id: 8, 
    receiptDate: 'Snow', 
    wagon: 'Jon', 
    type: 'Jon', 
    wheelPairNum: 'Jon', 
    manufacturerStamp: 'Jon', 
    created_at: randomDate(new Date(2012, 0, 1), new Date()).getFullYear(), 
    CKKLeft: 1, 
    CKKRight: 2, 
    rimThicknessLeft: 3, 
    rimThicknessRight: 4, 
    ridgeThicknessLeft: 6, 
    ridgeThicknessRight: 7, 
    wheelPairType: '1 вид', 
    note: 'Jon', 
  },
  { 
    id: 9, 
    receiptDate: 'Snow', 
    wagon: 'Jon', 
    type: 'Jon', 
    wheelPairNum: 'Jon', 
    manufacturerStamp: 'Jon', 
    created_at: randomDate(new Date(2012, 0, 1), new Date()).getFullYear(), 
    CKKLeft: 1, 
    CKKRight: 2, 
    rimThicknessLeft: 3, 
    rimThicknessRight: 4, 
    ridgeThicknessLeft: 6, 
    ridgeThicknessRight: 7, 
    wheelPairType: '1 вид', 
    note: 'Jon', 
  },
  { 
    id: 10, 
    receiptDate: 'Snow', 
    wagon: 'Jon', 
    type: 'Jon', 
    wheelPairNum: 'Jon', 
    manufacturerStamp: 'Jon', 
    created_at: randomDate(new Date(2012, 0, 1), new Date()).getFullYear(), 
    CKKLeft: 1, 
    CKKRight: 2, 
    rimThicknessLeft: 3, 
    rimThicknessRight: 4, 
    ridgeThicknessLeft: 6, 
    ridgeThicknessRight: 7, 
    wheelPairType: '1 вид', 
    note: 'Jon', 
  },
  { 
    id: 11, 
    receiptDate: 'Snow', 
    wagon: 'Jon', 
    type: 'Jon', 
    wheelPairNum: 'Jon', 
    manufacturerStamp: 'Jon', 
    created_at: randomDate(new Date(2012, 0, 1), new Date()).getFullYear(), 
    CKKLeft: 1, 
    CKKRight: 2, 
    rimThicknessLeft: 3, 
    rimThicknessRight: 4, 
    ridgeThicknessLeft: 6, 
    ridgeThicknessRight: 7, 
    wheelPairType: '1 вид', 
    note: 'Jon', 
  },
  { 
    id: 12, 
    receiptDate: 'Snow', 
    wagon: 'Jon', 
    type: 'Jon', 
    wheelPairNum: 'Jon', 
    manufacturerStamp: 'Jon', 
    created_at: randomDate(new Date(2012, 0, 1), new Date()).getFullYear(), 
    CKKLeft: 1, 
    CKKRight: 2, 
    rimThicknessLeft: 3, 
    rimThicknessRight: 4, 
    ridgeThicknessLeft: 6, 
    ridgeThicknessRight: 7, 
    wheelPairType: '1 вид', 
    note: 'Jon', 
  },
];

// const deleteRow = React.useCallback(
//   (id: GridRowId) => () => {
//     setTimeout(() => {
//       setRows((prevRows) => prevRows.filter((row) => row.id !== id));
//     });
//   },
//   [],
// );